
# Función para análisis de imágenes de plantas - acceso público
[functions.analyze-image]
verify_jwt = false

# Función para completar información de plantas
[functions.complete-plant-info]
verify_jwt = false

# Función para respuesta de plantas en chat
[functions.generate-plant-response]
verify_jwt = false

# Función para análisis de progreso de imágenes
[functions.analyze-progress-images]
verify_jwt = false

# Función para chat de jardín - requiere autenticación
[functions.garden-ai-chat]
verify_jwt = true

[functions.generate-plant-insights]
enabled = true
verify_jwt = true
import_map = "./functions/generate-plant-insights/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-plant-insights/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-plant-insights/*.html" ]
